TITLE	 lastfeatures.hpp
SUBTITLE This file was automatically generated by the 32-bit H++ Compiler


	.486P
	.MODEL flat,stdcall
	.STACK 000100000h
	INCLUDE stdhpp\hcclib32.INC	; the H++ library.

;Windows API prototypes
GetVersion PROTO

;This assembly file was generated by the 32-bit H++ Compiler

.CODE ;code segment
LastFeatures_DoubleProxy PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 LastFeatures_SimpleObject ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__LastFeatures_DoubleProxy 
	mov	ECX,dword ptr [EBP-0004h] 
	call	 __member_Init@LastFeatures_DoubleProxy 
	lea	EAX,OFFSET $S000702
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_DoubleProxy ENDP

LastFeatures_DoubleProxy_Swap PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000010h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0010h],ECX
	mov	ECX,dword ptr [EBP-0010h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	fstp	qword ptr [EBP-0008h]
	pop	EDX
	pop	EAX 
	mov	EAX,dword ptr [EBP+0008h]
	lea	EBX,dword ptr [EBP-000Ch]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-12]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0010h]
	fstp	qword ptr [ECX+0004h]
	pop	EDX
	pop	EAX 
	mov	ECX,dword ptr [EBP-12]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,dword ptr [EBP-0008h]
	mov	EAX,dword ptr [EBP-0004h] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
$L000709:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
LastFeatures_DoubleProxy_Swap ENDP

LastFeatures_DoubleProxy_isEqual PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000008h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0008h],ECX
	mov	EAX,dword ptr [EBP+0008h]
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-0008h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-4]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	call	 FloatingPoint_Compare
	cmp	EAX,000000000h
	neg	EAX
	setl	AL
	jmp	OFFSET $L000706
$L000706:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
LastFeatures_DoubleProxy_isEqual ENDP

LastFeatures_DoubleProxy_lessThan PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000008h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0008h],ECX
	mov	EAX,dword ptr [EBP+0008h]
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-0008h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-4]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	call	 FloatingPoint_Compare
	cmp	EAX,000000000h
	neg	EAX
	setl	AL
	jmp	OFFSET $L000703
$L000703:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
LastFeatures_DoubleProxy_lessThan ENDP

LastFeatures_HObject_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
$L000727:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_HObject_Destructor ENDP

LastFeatures_HObject PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__LastFeatures_HObject 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_HObject ENDP

LastFeatures_SimpleObject_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000697
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000696:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_SimpleObject_Destructor ENDP

LastFeatures_SimpleObject PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__LastFeatures_SimpleObject 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_SimpleObject ENDP

LastFeatures_SortDoubleProxy_Sort PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,00000000Ch
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-000Ch],ECX
	mov	EAX,000000001h
	mov	dword ptr [EBP-0004h],EAX
	jmp	OFFSET $L000792
$L000793:
	mov	EAX,dword ptr [EBP-4]
	inc	dword ptr [EBP-4]
$L000792:
	mov	EAX,dword ptr [EBP-0004h]
	push	EAX
	mov	EAX,dword ptr [EBP+000Ch]
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	OFFSET $L000794
	xor	EAX,EAX
	mov	dword ptr [EBP-0008h],EAX
	jmp	OFFSET $L000795
$L000796:
	mov	EAX,dword ptr [EBP-8]
	inc	dword ptr [EBP-8]
$L000795:
	mov	EAX,dword ptr [EBP-0008h]
	push	EAX
	mov	EAX,dword ptr [EBP-0004h]
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	OFFSET $L000797
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	push	EAX
	mov	EAX,dword ptr [EBP-0008h]
	push	EAX
	mov	EAX,000000001h
	pop	EDX
	add	EAX,EDX
	pop	ESI
	lea	ECX,dword ptr [ESI+EAX*0004h]
	push	ECX
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	push	EAX
	mov	EAX,dword ptr [EBP-0008h]
	pop	ESI
	lea	ECX,dword ptr [ESI+EAX*0004h]
	push	ECX
	mov	ECX,dword ptr [ESP+0004h]
	mov	EDX,dword ptr [ECX] 
	call	dword ptr [EDX]
	pop	ECX
	test	AL,AL
	jz	OFFSET $L000798
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	push	EAX
	mov	EAX,dword ptr [EBP-0008h]
	push	EAX
	mov	EAX,000000001h
	pop	EDX
	add	EAX,EDX
	pop	ESI
	lea	ECX,dword ptr [ESI+EAX*0004h]
	push	ECX
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	push	EAX
	mov	EAX,dword ptr [EBP-0008h]
	pop	ESI
	lea	ECX,dword ptr [ESI+EAX*0004h]
	push	ECX
	mov	ECX,dword ptr [ESP+0004h]
	mov	EDX,dword ptr [ECX] 
	call	dword ptr [EDX+0008h]
	pop	ECX
$L000798:
	jmp	OFFSET $L000796 
$L000797:
	jmp	OFFSET $L000793 
$L000794:
$L000720:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
LastFeatures_SortDoubleProxy_Sort ENDP

LastFeatures_SwapperObject_Swap PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000010h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0010h],ECX
	lea	ECX,dword ptr [EBP-000Ch]
	call	 LastFeatures_DoubleProxy
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	mov	ESI,ECX
	lea	EBX,dword ptr [EBP-000Ch]
	mov	EDI,EBX 
	mov	ECX,00000000Ch 
	cld	
	rep movsb	
	mov	EBX,dword ptr [EBP+000Ch]
	mov	EAX,EBX 
	mov	ESI,ECX
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	mov	EDI,EBX 
	mov	ECX,00000000Ch 
	cld	
	rep movsb	
	lea	ECX,dword ptr [EBP-000Ch]
	mov	ESI,ECX
	mov	EBX,dword ptr [EBP+000Ch]
	mov	EAX,EBX 
	mov	EDI,EBX 
	mov	ECX,00000000Ch 
	cld	
	rep movsb	
$L000714:
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+000Ch]
$L000800:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
LastFeatures_SwapperObject_Swap ENDP

LastFeatures_SwapperObject PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__LastFeatures_SwapperObject 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_SwapperObject ENDP

LastFeatures_TestProperties_get_Shapes PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	jmp	OFFSET $L000743
$L000743:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_TestProperties_get_Shapes ENDP

LastFeatures_TestProperties_put_Shapes PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000098h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0098h],ECX
	lea	ECX,dword ptr [EBP-000Ch]
	call	 LastFeatures_TestProperties_node
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX]
	push	EAX
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000802
	mov	ESI,EAX
	jmp	 $L000803
$L000802:
	xor	ESI,ESI
$L000803:
	pop	EBX
	mov	dword ptr [EBX],ESI 
	mov	ECX,ESI
	call	 LastFeatures_TestProperties_node
	mov	EAX,ESI 
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000804
	mov	ESI,EAX
	jmp	 $L000805
$L000804:
	xor	ESI,ESI
$L000805:
	pop	EBX
	mov	dword ptr [EBX],ESI 
	mov	ECX,ESI
	call	 LastFeatures_TestProperties_node
	mov	EAX,ESI 
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX+0008h]
	push	EAX
	push	000000004h
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000806
	mov	ESI,EAX
	jmp	 $L000807
$L000806:
	xor	ESI,ESI
$L000807:
	pop	EBX
	mov	dword ptr [EBX],ESI 
	mov	ECX,ESI
	call	 LastFeatures_HObject
	mov	EAX,ESI 
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	lea	EBX,dword ptr [EBP-0010h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-16]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000809
	call	 LastFeatures_TestProperties_node_Destructor
$L000809:
	push	ESI
	call	 System_Memory_Destroy
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX]
	push	EAX
	xor	EAX,EAX
	pop	EBX
	mov	dword ptr [EBX],EAX
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX]
	push	EAX
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	pop	EBX
	mov	dword ptr [EBX],EAX
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000810
	mov	ESI,EAX
	jmp	 $L000811
$L000810:
	xor	ESI,ESI
$L000811:
	pop	EBX
	mov	dword ptr [EBX],ESI 
	mov	ECX,ESI
	call	 LastFeatures_TestProperties_node
	mov	EAX,ESI 
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	lea	EBX,dword ptr [EBP-0014h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-20]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000813
	call	 LastFeatures_TestProperties_node_Destructor
$L000813:
	push	ESI
	call	 System_Memory_Destroy
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	pop	EBX
	mov	dword ptr [EBX],EAX
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX]
	push	EAX
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000814
	mov	ESI,EAX
	jmp	 $L000815
$L000814:
	xor	ESI,ESI
$L000815:
	pop	EBX
	mov	dword ptr [EBX],ESI 
	mov	ECX,ESI
	call	 LastFeatures_TestProperties_node
	mov	EAX,ESI 
	lea	ECX,dword ptr [EBP-000Ch]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	lea	EBX,dword ptr [EBP-0010h]
	mov	dword ptr [EBX],EAX
	lea	ECX,dword ptr [EBP-000Ch]
	lea	EAX,dword ptr [ECX]
	push	EAX
	mov	EAX,dword ptr [EBP-16]
	pop	EBX
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	push	EAX
	xor	EAX,EAX
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	push	EAX
	xor	EAX,EAX
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	ECX,EAX 
	push	EAX
	xor	EAX,EAX
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	push	EAX
	mov	EAX,000000001h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	push	EAX
	mov	EAX,000000002h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	ECX,EAX 
	push	EAX
	mov	EAX,000000003h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	push	EAX
	xor	EAX,EAX
	pop	EDX
	cmp	EDX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000816
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	test	EAX,EAX
	jz	OFFSET $L000818
	push	EAX
	call	 System_Memory_Destroy
$L000818:
$L000816:
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	test	EAX,EAX
	jz	OFFSET $L000819
	mov	ESI,EAX
	mov	ECX,dword ptr [ESI-0004h]
	lea	EDI,dword ptr [ESI+ECX]
	mov	EBX,ESI 
$L000820:
	mov	ECX,EBX 
	test	ECX,ECX
	jz	OFFSET $L000821
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+0010h]
$L000821:
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000820

	add	ESI,0FFFFFFFCh
	push	ESI
	call	 System_Memory_Destroy
$L000819:
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	mov	ECX,dword ptr [EBP-0098h]
	mov	dword ptr [ECX],EAX
	mov	ECX,dword ptr [EBP-0098h]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	test	EAX,EAX
	jz	OFFSET $L000822
	mov	ESI,EAX
	mov	ECX,dword ptr [ESI-0004h]
	lea	EDI,dword ptr [ESI+ECX]
	mov	EBX,ESI 
$L000823:
	mov	ECX,EBX 
	test	ECX,ECX
	jz	OFFSET $L000824
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+0010h]
$L000824:
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000823

	add	ESI,0FFFFFFFCh
	push	ESI
	call	 System_Memory_Destroy
$L000822:
	lea	EAX,dword ptr [EBP-008Ch]
	mov	ESI,EAX
	lea	EDI,dword ptr [ESI+120]
	mov	EBX,ESI
$L000825:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000825
	xor	EAX,EAX
	imul	EAX,EAX,00000000Ch
	lea	ECX,dword ptr [EBP+EAX-008Ch]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	EAX,000000002h
	imul	EAX,EAX,00000000Ch
	lea	ECX,dword ptr [EBP+EAX-008Ch]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	xor	EAX,EAX
	mov	dword ptr [EBP-0090h],EAX
	jmp	OFFSET $L000826
$L000827:
	mov	EAX,dword ptr [EBP-144]
	inc	dword ptr [EBP-144]
$L000826:
	mov	EAX,dword ptr [EBP-0090h]
	push	EAX
	mov	EAX,00000000Ah
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	OFFSET $L000828
	mov	EAX,dword ptr [EBP-0090h]
	imul	EAX,EAX,00000000Ch
	lea	ECX,dword ptr [EBP+EAX-008Ch]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	jmp	OFFSET $L000827 
$L000828:
	mov	EAX,000000005h
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000829
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000830
$L000829:
	xor	ESI,ESI
$L000830:
	mov	dword ptr [EBP-0094h],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000831:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000831
	mov	EAX,ESI 
	mov	EAX,dword ptr [EBP-148]
	push	EAX
	xor	EAX,EAX
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	EAX,dword ptr [EBP-148]
	test	EAX,EAX
	jz	OFFSET $L000832
	mov	ESI,EAX
	mov	ECX,dword ptr [ESI-0004h]
	lea	EDI,dword ptr [ESI+ECX]
	mov	EBX,ESI 
$L000833:
	mov	ECX,EBX 
	test	ECX,ECX
	jz	OFFSET $L000834
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+0010h]
$L000834:
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000833

	add	ESI,0FFFFFFFCh
	push	ESI
	call	 System_Memory_Destroy
$L000832:
$L000744:
	lea	EAX,dword ptr [EBP-008Ch]
	mov	ESI,EAX 
	lea	EDI,dword ptr [ESI+120]
	mov	EBX,ESI
$L000836:
	mov	ECX,EBX 
	test	ECX,ECX
	jz	OFFSET $L000837
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+0010h]
$L000837:
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000836

	lea	ECX,dword ptr [EBP-000Ch]
	call	 LastFeatures_TestProperties_node_Destructor
$L000838:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
LastFeatures_TestProperties_put_Shapes ENDP

LastFeatures_TestProperties PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 __member_Init@LastFeatures_TestProperties

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_TestProperties ENDP

LastFeatures_TestProperties_node_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	push	ECX
	xor	EAX,EAX
	pop	EBX
	cmp	EBX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000840
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000843
	call	 LastFeatures_TestProperties_node_Destructor
$L000843:
	push	ESI
	call	 System_Memory_Destroy
$L000840:
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	push	ECX
	xor	EAX,EAX
	pop	EBX
	cmp	EBX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000844
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0004h]
	mov	ECX,EAX 
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000847
	call	 LastFeatures_TestProperties_node_Destructor
$L000847:
	push	ESI
	call	 System_Memory_Destroy
$L000844:
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	ECX,EAX 
	push	ECX
	xor	EAX,EAX
	pop	EBX
	cmp	EBX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000848
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	ECX,EAX 
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000851
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX]
$L000851:
	push	ESI
	call	 System_Memory_Destroy
$L000848:
$L000735:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_TestProperties_node_Destructor ENDP

LastFeatures_TestProperties_node PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 __member_Init@LastFeatures_TestProperties_node

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
LastFeatures_TestProperties_node ENDP

Math_DegreesToRadians PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_pi
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,0000000B4h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000464
$L000464:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_DegreesToRadians ENDP

Math_Hyperbolic_HCos PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000002h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000481
$L000481:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HCos ENDP

Math_Hyperbolic_HCosec PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000002h
	push	EAX
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000487
$L000487:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HCosec ENDP

Math_Hyperbolic_HCotan PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000489
$L000489:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HCotan ENDP

Math_Hyperbolic_HSec PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000002h
	push	EAX
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000485
$L000485:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HSec ENDP

Math_Hyperbolic_HSin PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	mov	EAX,000000002h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000478
$L000478:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HSin ENDP

Math_Hyperbolic_HTan PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Exp
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	call	 Math_Exp
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000483
$L000483:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_HTan ENDP

Math_Hyperbolic_Inverse_HArccos PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	call	 Math_Sqrt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	jmp	OFFSET $L000495
$L000495:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArccos ENDP

Math_Hyperbolic_Inverse_HArccosec PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	call	 Math_Sign
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Sqrt
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	jmp	OFFSET $L000501
$L000501:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArccosec ENDP

Math_Hyperbolic_Inverse_HArccotan PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	push	EAX
	push	EDX 
	mov	EAX,000000002h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000503
$L000503:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArccotan ENDP

Math_Hyperbolic_Inverse_HArcsec PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Sqrt
	push	EAX
	push	EDX 
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	jmp	OFFSET $L000499
$L000499:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArcsec ENDP

Math_Hyperbolic_Inverse_HArcsin PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Sqrt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	jmp	OFFSET $L000492
$L000492:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArcsin ENDP

Math_Hyperbolic_Inverse_HArctan PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000001h
	push	EAX
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000001h
	push	EAX
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	call	 Math_Ln
	push	EAX
	push	EDX 
	mov	EAX,000000002h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000497
$L000497:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_Hyperbolic_Inverse_HArctan ENDP

Math_RadiansToDegrees PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,0000000B4h
	push	EAX
	call	 Math_pi
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000461
$L000461:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
Math_RadiansToDegrees ENDP

UnitTesting_Circle_Circumference PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	call	 Math_pi
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Circle_get_Radius
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000612
$L000612:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_Circumference ENDP

UnitTesting_Circle_ComputeArea PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000002h
	push	EAX
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Circle_Circumference
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000618
$L000618:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_ComputeArea ENDP

UnitTesting_Circle_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000620
	push	EAX
	call	 System_Debug_OutputString
	lea	EAX,OFFSET $S000620
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000619:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_Destructor ENDP

UnitTesting_Circle_Draw PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000617
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000616:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_Draw ENDP

UnitTesting_Circle_DrawSphere PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000622
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000621:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_DrawSphere ENDP

UnitTesting_Circle_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000615
	jmp	OFFSET $L000614
$L000614:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_Name ENDP

UnitTesting_Circle_get_Radius PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	jmp	OFFSET $L000609
$L000609:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_get_Radius ENDP

UnitTesting_Circle_put_Radius PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
$L000610:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_Circle_put_Radius ENDP

UnitTesting_Circle_Type PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000001h
	jmp	OFFSET $L000613
$L000613:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle_Type ENDP

UnitTesting_Circle PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Shape ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_Circle 
	mov	ECX,dword ptr [EBP-0004h] 
	call	 __member_Init@UnitTesting_Circle 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Circle ENDP

UnitTesting_Rnd_NextDbl PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	call	 UnitTesting_Rnd_NextDblEx
	jmp	OFFSET $L000535
$L000535:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Rnd_NextDbl ENDP

UnitTesting_Rnd_NextInt PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	call	 UnitTesting_Rnd_NextIntEx
	jmp	OFFSET $L000536
$L000536:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Rnd_NextInt ENDP

UnitTesting_Rnd PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 __member_Init@UnitTesting_Rnd
	mov	EAX,dword ptr [EBP+0008h]
	mov	 UnitTesting_Rnd_seed,EAX

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
UnitTesting_Rnd ENDP

UnitTesting_Rnd_setSeed PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,dword ptr [EBP+0008h]
	mov	 UnitTesting_Rnd_seed,EAX
$L000530:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
UnitTesting_Rnd_setSeed ENDP

UnitTesting_Rnd_NextDblEx PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EBX,OFFSET UnitTesting_Rnd_a
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_q
	mov	EAX,dword ptr [EBX]
	mov	ECX,EAX
	pop	EAX
	xor	EDX,EDX
	idiv	ECX
	mov	EAX,EDX 
	pop	ECX
	cdq	
	imul	EAX,ECX
	push	EDX
	push	EAX 
	lea	EBX,OFFSET UnitTesting_Rnd_r
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_q
	mov	EAX,dword ptr [EBX]
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fclex
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt64
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fistp	qword ptr [ESP]
	pop	EAX
	pop	EDX 
	mov	 UnitTesting_Rnd_seed,EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	xor	EAX,EAX
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	 $L000852
	lea	EBX,OFFSET UnitTesting_Rnd_m
	mov	EAX,dword ptr [EBX]
	jmp	 $L000853
$L000852:
	xor	EAX,EAX
$L000853:
	clc	
	add	 UnitTesting_Rnd_seed,EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_m
	mov	EAX,dword ptr [EBX]
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000532
$L000532:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Rnd_NextDblEx ENDP

UnitTesting_Rnd_NextIntEx PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EBX,OFFSET UnitTesting_Rnd_a
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_q
	mov	EAX,dword ptr [EBX]
	mov	ECX,EAX
	pop	EAX
	xor	EDX,EDX
	idiv	ECX
	mov	EAX,EDX 
	pop	ECX
	cdq	
	imul	EAX,ECX
	push	EDX
	push	EAX 
	lea	EBX,OFFSET UnitTesting_Rnd_r
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_q
	mov	EAX,dword ptr [EBX]
	pop	ECX
	cdq	
	imul	EAX,ECX
	fclex
	push	EDX
	push	EAX 
	call	 FloatingPoint_FromInt64
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fmul	qword ptr [ESP]
	fistp	qword ptr [ESP]
	call	 FloatingPoint_FromInt64
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	call	 FloatingPoint_FromInt64
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fistp	qword ptr [ESP]
	pop	EAX
	pop	EDX 
	mov	 UnitTesting_Rnd_seed,EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	xor	EAX,EAX
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	 $L000854
	lea	EBX,OFFSET UnitTesting_Rnd_m
	mov	EAX,dword ptr [EBX]
	jmp	 $L000855
$L000854:
	xor	EAX,EAX
$L000855:
	clc	
	add	 UnitTesting_Rnd_seed,EAX
	lea	EBX,OFFSET UnitTesting_Rnd_seed
	mov	EAX,dword ptr [EBX]
	push	EAX
	lea	EBX,OFFSET UnitTesting_Rnd_m
	mov	EAX,dword ptr [EBX]
	mov	ECX,EAX
	pop	EAX
	xor	EDX,EDX
	idiv	ECX
	mov	EAX,EDX 
	push	EAX
	call	 FloatingPoint_FromInt
	jmp	OFFSET $L000534
$L000534:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Rnd_NextIntEx ENDP

UnitTesting_Shape PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_Shape 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Shape ENDP

UnitTesting_ShapeFactoryCreator_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	push	ECX
	xor	EAX,EAX
	pop	EBX
	cmp	EBX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000857
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000860
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000860:
	push	ESI
	call	 System_Memory_Destroy
$L000857:
	xor	EAX,EAX
	push	EAX
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	pop	ECX
	cmp	ECX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000861
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX]
	mov	ECX,EAX 
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000864
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000864:
	push	ESI
	call	 System_Memory_Destroy
$L000861:
$L000674:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_ShapeFactoryCreator_Destructor ENDP

UnitTesting_ShapeFactoryCreator PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 __member_Init@UnitTesting_ShapeFactoryCreator

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_ShapeFactoryCreator ENDP

UnitTesting_ShapeFactoryCreator_Create PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000008h
	push	EBX 
	push	ESI 
	push	EDI 
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000866
	mov	ESI,EAX
	jmp	 $L000867
$L000866:
	xor	ESI,ESI
$L000867:
	mov	dword ptr [EBP-0004h],ESI 
	mov	ECX,ESI
	call	 UnitTesting_Circle
	mov	EAX,ESI 
	mov	ECX,dword ptr [EBP-4]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000869
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000869:
	push	ESI
	call	 System_Memory_Destroy
	mov	EAX,dword ptr [EBP+0008h]
	push	EAX
	lea	EAX,OFFSET $S000615
	pop	EDI
	mov	ESI,EAX
	push	EAX
	call	 StringHandling_StringLength
	push	EAX 
	push	ESI 
	push	EDI 
	call	 StringHandling_StringCompare 
	cmp	EAX,000000000h
	setz	AL
	test	AL,AL
	jz	OFFSET $L000870
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000872
	mov	ESI,EAX
	jmp	 $L000873
$L000872:
	xor	ESI,ESI
$L000873:
	mov	ECX,ESI
	call	 UnitTesting_Circle
	mov	EAX,ESI 
	jmp	OFFSET $L000671
	jmp	OFFSET $L000871

; else {
$L000870:
	mov	EAX,dword ptr [EBP+0008h]
	push	EAX
	lea	EAX,OFFSET $S000641
	pop	EDI
	mov	ESI,EAX
	push	EAX
	call	 StringHandling_StringLength
	push	EAX 
	push	ESI 
	push	EDI 
	call	 StringHandling_StringCompare 
	cmp	EAX,000000000h
	setz	AL
	test	AL,AL
	jz	OFFSET $L000874
	push	000000014h
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000876
	mov	ESI,EAX
	jmp	 $L000877
$L000876:
	xor	ESI,ESI
$L000877:
	mov	ECX,ESI
	call	 UnitTesting_Square
	mov	EAX,ESI 
	jmp	OFFSET $L000671
	jmp	OFFSET $L000875

; else {
$L000874:
	mov	EAX,dword ptr [EBP+0008h]
	push	EAX
	lea	EAX,OFFSET $S000661
	pop	EDI
	mov	ESI,EAX
	push	EAX
	call	 StringHandling_StringLength
	push	EAX 
	push	ESI 
	push	EDI 
	call	 StringHandling_StringCompare 
	cmp	EAX,000000000h
	setz	AL
	test	AL,AL
	jz	OFFSET $L000878
	push	000000014h
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000880
	mov	ESI,EAX
	jmp	 $L000881
$L000880:
	xor	ESI,ESI
$L000881:
	mov	ECX,ESI
	call	 UnitTesting_Triangle
	mov	EAX,ESI 
	jmp	OFFSET $L000671
$L000878:
$L000875:

; }
$L000871:

; }
	xor	EAX,EAX
	jmp	OFFSET $L000671
$L000671:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
UnitTesting_ShapeFactoryCreator_Create ENDP

UnitTesting_Square_ComputeArea PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Square_get_Width
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Square_get_Height
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000638
$L000638:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_ComputeArea ENDP

UnitTesting_Square_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000629
	push	EAX
	call	 System_Debug_OutputString
	lea	EAX,OFFSET $S000629
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000628:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_Destructor ENDP

UnitTesting_Square_Draw PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000643
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000642:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_Draw ENDP

UnitTesting_Square_DrawCube PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000645
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000644:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_DrawCube ENDP

UnitTesting_Square_get_Height PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0010h]
	mov	EDX,dword ptr [ECX+000Ch] 
	jmp	OFFSET $L000635
$L000635:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_get_Height ENDP

UnitTesting_Square_put_Height PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+000Ch]
$L000636:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_Square_put_Height ENDP

UnitTesting_Square_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000641
	jmp	OFFSET $L000640
$L000640:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_Name ENDP

UnitTesting_Square_Type PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000002h
	jmp	OFFSET $L000639
$L000639:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_Type ENDP

UnitTesting_Square PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Shape ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_Square 
	mov	ECX,dword ptr [EBP-0004h] 
	call	 __member_Init@UnitTesting_Square 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square ENDP

UnitTesting_Square_get_Width PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	jmp	OFFSET $L000631
$L000631:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Square_get_Width ENDP

UnitTesting_Square_put_Width PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
$L000632:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_Square_put_Width ENDP

UnitTesting_TestSwitch_RunTest PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,dword ptr [EBP+0008h]
	mov	ESI,EAX
	mov	EAX,000000001h
	cmp	EAX,ESI
	jz	OFFSET $L000883
	mov	EAX,000000002h
	cmp	EAX,ESI
	jz	OFFSET $L000884
	mov	EAX,000000003h
	cmp	EAX,ESI
	jz	OFFSET $L000885
	mov	EAX,000000004h
	cmp	EAX,ESI
	jz	OFFSET $L000886
	mov	EAX,000000005h
	cmp	EAX,ESI
	jz	OFFSET $L000887
	mov	EAX,000000006h
	cmp	EAX,ESI 
	jz	OFFSET $L000888 
	jmp	OFFSET $L000889
$L000883:
	lea	EAX,OFFSET $S000583
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000882
$L000884:
	lea	EAX,OFFSET $S000584
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000882
$L000885:
	lea	EAX,OFFSET $S000585
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000882
$L000886:
	lea	EAX,OFFSET $S000586
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000882
$L000887:
	lea	EAX,OFFSET $S000588
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000888:
	lea	EAX,OFFSET $S000590
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000882
$L000889:
	lea	EAX,OFFSET $S000591
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	mov	EAX,dword ptr [EBP+0008h]
	push	EAX 
	call	 Console_WriteInteger 
	call	 Console_WriteCrLf 
$L000882:
$L000581:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
UnitTesting_TestSwitch_RunTest ENDP

UnitTesting_TestVirtuals_ExponentialRV_get_MU PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	jmp	OFFSET $L000570
$L000570:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_ExponentialRV_get_MU ENDP

UnitTesting_TestVirtuals_ExponentialRV_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000575
	jmp	OFFSET $L000574
$L000574:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_ExponentialRV_Name ENDP

UnitTesting_TestVirtuals_ExponentialRV_Sample PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_ExponentialRV_get_MU
	push	EAX
	push	EDX 
	call	 UnitTesting_Rnd_NextDblEx
	push	EAX
	push	EDX 
	call	 Math_log10
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fld	qword ptr [ESP]
	fchs
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000573
$L000573:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_ExponentialRV_Sample ENDP

UnitTesting_TestVirtuals_ExponentialRV PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_RandomVariable ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_TestVirtuals_ExponentialRV 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_TestVirtuals_ExponentialRV ENDP

UnitTesting_TestVirtuals_RandomVariable_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000542
	jmp	OFFSET $L000541
$L000541:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_RandomVariable_Name ENDP

UnitTesting_TestVirtuals_RandomVariable PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_TestVirtuals_RandomVariable 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_RandomVariable ENDP

UnitTesting_TestVirtuals_SimpleRV_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000547
	jmp	OFFSET $L000546
$L000546:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_SimpleRV_Name ENDP

UnitTesting_TestVirtuals_SimpleRV_Sample PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	call	 UnitTesting_Rnd_NextDblEx
	jmp	OFFSET $L000545
$L000545:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_SimpleRV_Sample ENDP

UnitTesting_TestVirtuals_SimpleRV PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_RandomVariable ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_TestVirtuals_SimpleRV 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_SimpleRV ENDP

UnitTesting_TestVirtuals_UniformRV_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000565
	jmp	OFFSET $L000564
$L000564:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_UniformRV_Name ENDP

UnitTesting_TestVirtuals_UniformRV_Sample PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0010h]
	mov	EDX,dword ptr [ECX+000Ch] 
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fld	qword ptr [ESP]
	fsub	st,st(1)
	fstp	qword ptr [ESP]
	call	 UnitTesting_Rnd_NextDblEx
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fadd	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000563
$L000563:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_UniformRV_Sample ENDP

UnitTesting_TestVirtuals_UniformRV_get_U PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	jmp	OFFSET $L000553
$L000553:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_UniformRV_get_U ENDP

UnitTesting_TestVirtuals_UniformRV_put_U PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
$L000554:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_TestVirtuals_UniformRV_put_U ENDP

UnitTesting_TestVirtuals_UniformRV PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_RandomVariable ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_TestVirtuals_UniformRV 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_UniformRV_put_U
	mov	EDX,dword ptr [EBP+0010h]
	mov	EAX,dword ptr [EBP+0014h] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_TestVirtuals_UniformRV_put_V

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000010h
UnitTesting_TestVirtuals_UniformRV ENDP

UnitTesting_TestVirtuals_UniformRV_get_V PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0010h]
	mov	EDX,dword ptr [ECX+000Ch] 
	jmp	OFFSET $L000557
$L000557:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_TestVirtuals_UniformRV_get_V ENDP

UnitTesting_TestVirtuals_UniformRV_put_V PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+000Ch]
$L000558:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_TestVirtuals_UniformRV_put_V ENDP

UnitTesting_Triangle_get_Base PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0008h]
	mov	EDX,dword ptr [ECX+0004h] 
	jmp	OFFSET $L000652
$L000652:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_get_Base ENDP

UnitTesting_Triangle_put_Base PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
$L000653:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_Triangle_put_Base ENDP

UnitTesting_Triangle_ComputeArea PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Triangle_get_Base
	push	EAX
	push	EDX 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Triangle_get_High
	fclex
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX
	pop	ECX 
	fmul	qword ptr [ESP]
	fstp	qword ptr [ESP]
	mov	EAX,000000002h
	fclex
	push	EAX
	call	 FloatingPoint_FromInt
	push	EAX
	push	EDX 
	fld	qword ptr [ESP]
	pop	ECX 
	pop	ECX 
	fdivr	qword ptr [ESP]
	fstp	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	jmp	OFFSET $L000664
$L000664:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_ComputeArea ENDP

UnitTesting_Triangle_Destructor PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000666
	push	EAX
	call	 System_Debug_OutputString
	lea	EAX,OFFSET $S000666
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000665
$L000665:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_Destructor ENDP

UnitTesting_Triangle_Draw PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000663
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000662:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_Draw ENDP

UnitTesting_Triangle_DrawPiramid PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000668
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
$L000667:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_DrawPiramid ENDP

UnitTesting_Triangle_get_High PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	mov	EAX,dword ptr [ECX+0010h]
	mov	EDX,dword ptr [ECX+000Ch] 
	jmp	OFFSET $L000656
$L000656:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_get_High ENDP

UnitTesting_Triangle_put_High PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EDX,dword ptr [EBP+0008h]
	mov	EAX,dword ptr [EBP+000Ch] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+000Ch]
$L000657:
	pop	EDX
	pop	EAX 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
UnitTesting_Triangle_put_High ENDP

UnitTesting_Triangle_Name PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	lea	EAX,OFFSET $S000661
	jmp	OFFSET $L000660
$L000660:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_Name ENDP

UnitTesting_Triangle_Type PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	EAX,000000003h
	jmp	OFFSET $L000659
$L000659:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle_Type ENDP

UnitTesting_Triangle PROC NEAR 
	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	ECX,dword ptr [EBP-0004h]
	call	 UnitTesting_Shape ;base constructor call
	mov	ECX,dword ptr [EBP-0004h] 
	mov	dword ptr [ECX],OFFSET  @@class_vptr_vtbl@@__UnitTesting_Triangle 
	mov	ECX,dword ptr [EBP-0004h] 
	call	 __member_Init@UnitTesting_Triangle 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
UnitTesting_Triangle ENDP

UnitTesting_Visitor_Visit PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,000000014h
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0014h],ECX
	mov	ECX,dword ptr [EBP+0008h]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	xor	EAX,EAX
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP+0008h]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX]
	mov	ESI,EAX
	mov	EAX,000000001h
	cmp	EAX,ESI
	jz	OFFSET $L000893
	mov	EAX,000000002h
	cmp	EAX,ESI
	jz	OFFSET $L000894
	mov	EAX,000000003h
	cmp	EAX,ESI
	jz	OFFSET $L000895
	jmp	OFFSET $L000896
$L000893:
	lea	EAX,OFFSET $S000679
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	lea	EBX,dword ptr [EBP-0008h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-8]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+0014h]
	mov	EAX,dword ptr [EBP-8]
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	jmp	OFFSET $L000892
$L000894:
	lea	EAX,OFFSET $S000681
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	lea	EBX,dword ptr [EBP-000Ch]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-12]
	call	 UnitTesting_Square_DrawCube
	mov	EAX,dword ptr [EBP-12]
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	jmp	OFFSET $L000892
$L000895:
	lea	EAX,OFFSET $S000683
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	call	 Console_WriteCrLf 
	mov	EBX,dword ptr [EBP+0008h]
	mov	EAX,EBX 
	lea	EBX,dword ptr [EBP-0010h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-16]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+0014h]
	mov	EAX,dword ptr [EBP-16]
	lea	EBX,dword ptr [EBP-0004h]
	mov	dword ptr [EBX],EAX
	jmp	OFFSET $L000892
$L000896:
	int	000000003h ;User breakpoint
$L000892:
	mov	EAX,dword ptr [EBP-4]
	mov	ECX,EAX 
	push	ECX
	xor	EAX,EAX
	pop	EBX
	cmp	EBX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000897
	mov	ECX,dword ptr [EBP-4]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
$L000897:
	xor	EAX,EAX
	push	EAX
	mov	EAX,dword ptr [EBP-4]
	pop	ECX
	cmp	ECX,EAX
	setnz	AL
	test	AL,AL
	jz	OFFSET $L000899
	mov	ECX,dword ptr [EBP-4]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
$L000899:
	lea	EAX,OFFSET $S000685
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	mov	ECX,dword ptr [EBP-4]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+0008h]
	push	000000000h 
	push	EAX 
	call	 Console_WriteString 
	call	 Console_WriteCrLf 
$L000676:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000004h
UnitTesting_Visitor_Visit ENDP

__member_Init@LastFeatures_DoubleProxy PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@LastFeatures_DoubleProxy ENDP
__member_Init@LastFeatures_TestProperties PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	mov	EAX,000000003h
	push	EAX
	mov	EAX,000000005h
	pop	ECX
	xor	EDX,EDX
	imul	EAX,ECX
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000901
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000902
$L000901:
	xor	ESI,ESI
$L000902:
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000903:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000903
	mov	EAX,ESI 
	mov	EAX,000000004h
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000904
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000905
$L000904:
	xor	ESI,ESI
$L000905:
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX+0004h],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000906:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000906
	mov	EAX,ESI 
	mov	EAX,000000004h
	push	EAX
	mov	EAX,000000005h
	pop	ECX
	xor	EDX,EDX
	imul	EAX,ECX
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000907
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000908
$L000907:
	xor	ESI,ESI
$L000908:
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX+0008h],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000909:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000909
	mov	EAX,ESI 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@LastFeatures_TestProperties ENDP
__member_Init@LastFeatures_TestProperties_node PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	xor	EAX,EAX
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],EAX
	xor	EAX,EAX
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX+0004h],EAX
	xor	EAX,EAX
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX+0008h],EAX

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@LastFeatures_TestProperties_node ENDP
__member_Init@UnitTesting_Circle PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@UnitTesting_Circle ENDP
__member_Init@UnitTesting_Rnd PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	mov	EAX,000000001h
	mov	 UnitTesting_Rnd_seed,EAX
	mov	EAX,0000041A7h
	mov	 UnitTesting_Rnd_a,EAX
	mov	EAX,07FFFFFFFh
	mov	 UnitTesting_Rnd_m,EAX
	mov	EAX,00001F31Dh
	mov	 UnitTesting_Rnd_q,EAX
	mov	EAX,000000B14h
	mov	 UnitTesting_Rnd_r,EAX

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@UnitTesting_Rnd ENDP
__member_Init@UnitTesting_ShapeFactoryCreator PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	push	00000000Ch
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000910
	mov	ESI,EAX
	jmp	 $L000911
$L000910:
	xor	ESI,ESI
$L000911:
	mov	ECX,dword ptr [EBP-0004h]
	mov	dword ptr [ECX],ESI 
	mov	ECX,ESI
	call	 UnitTesting_Circle
	mov	EAX,ESI 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@UnitTesting_ShapeFactoryCreator ENDP
__member_Init@UnitTesting_Square PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+000Ch]

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@UnitTesting_Square ENDP
__member_Init@UnitTesting_Triangle PROC NEAR

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	mov	dword ptr [EBP-0004h],ECX
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+0004h]
	fldz
	mov	ECX,dword ptr [EBP-0004h]
	fstp	qword ptr [ECX+000Ch]

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__member_Init@UnitTesting_Triangle ENDP
LastFeatures_TestFeatures_main PROC NEAR 
	push	EBP
	mov	EBP,ESP
	sub	ESP,00000007Ch
	push	EBX 
	push	ESI 
	push	EDI 
	xor	EAX,EAX
	mov	dword ptr [EBP-0004h],EAX
	jmp	OFFSET $L000912
$L000913:
	mov	EAX,dword ptr [EBP-4]
	inc	dword ptr [EBP-4]
$L000912:
	mov	EAX,dword ptr [EBP-0004h]
	push	EAX
	mov	EAX,dword ptr [EBP+0008h]
	pop	EDX
	cmp	EDX,EAX
	setl	AL
	test	AL,AL
	jz	OFFSET $L000914
	lea	EAX,OFFSET $S000758
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	mov	EAX,dword ptr [EBP-0004h]
	push	EAX 
	call	 Console_WriteInteger 
	lea	EAX,OFFSET $S000759
	push	000000000h 
	push	EAX 
	call	 Console_WriteString 
	mov	EBX,dword ptr [EBP+000Ch]
	mov	EAX,EBX 
	push	EAX
	mov	EAX,dword ptr [EBP-0004h]
	pop	ESI
	mov	EAX,dword ptr [ESI+EAX*0004h]
	push	000000000h 
	push	EAX 
	call	 Console_WriteString 
	call	 Console_WriteCrLf 
	jmp	OFFSET $L000913 
$L000914:
	int	000000003h ;User breakpoint
	lea	EAX,OFFSET $S000615
	push	EAX
	call	 UnitTesting_ShapeFactoryCreator_Create
	lea	EBX,dword ptr [EBP-0008h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-8]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	EAX,dword ptr [EBP-8]
	lea	EBX,dword ptr [EBP-000Ch]
	mov	dword ptr [EBX],EAX
	mov	EAX,dword ptr [EBP-8]
	lea	EBX,dword ptr [EBP-000Ch]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-12]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+0014h]
	mov	EAX,dword ptr [EBP-8]
	push	EAX
	lea	ECX,dword ptr [EBP-0010h]
	call	 UnitTesting_Visitor_Visit
	mov	ECX,dword ptr [EBP-8]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000916
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000916:
	push	ESI
	call	 System_Memory_Destroy
	lea	EAX,OFFSET $S000615
	push	EAX
	call	 UnitTesting_ShapeFactoryCreator_Create
	lea	EBX,dword ptr [EBP-0008h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-8]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-8]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000918
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000918:
	push	ESI
	call	 System_Memory_Destroy
	lea	EAX,OFFSET $S000661
	push	EAX
	call	 UnitTesting_ShapeFactoryCreator_Create
	lea	EBX,dword ptr [EBP-0008h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-8]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-8]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000920
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000920:
	push	ESI
	call	 System_Memory_Destroy
	lea	EAX,OFFSET $S000641
	push	EAX
	call	 UnitTesting_ShapeFactoryCreator_Create
	lea	EBX,dword ptr [EBP-0008h]
	mov	dword ptr [EBX],EAX
	mov	ECX,dword ptr [EBP-8]
	mov	EDX,dword ptr [ECX]
	call	dword ptr [EDX+000Ch]
	mov	ECX,dword ptr [EBP-8]
	mov	ESI,ECX
	test	ECX,ECX
	jz	OFFSET $L000922
	mov	EAX,dword ptr [ECX] 
	call	dword ptr [EAX+0010h]
$L000922:
	push	ESI
	call	 System_Memory_Destroy
	lea	ECX,dword ptr [EBP-0058h]
	call	 LastFeatures_TestProperties
	mov	EAX,000000014h
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000923
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000924
$L000923:
	xor	ESI,ESI
$L000924:
	mov	dword ptr [EBP-005Ch],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000925:
	mov	ECX,EBX 
	call	 UnitTesting_Circle
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000925
	mov	EAX,ESI 
	mov	EAX,dword ptr [EBP-92]
	push	EAX
	lea	ECX,dword ptr [EBP-0058h]
	call	 LastFeatures_TestProperties_put_Shapes
	mov	EAX,0DEADC0DEh
	mov	dword ptr [EBP-0060h],EAX
	mov	EAX,dword ptr [EBP-0060h]
	shl	EAX,000000010h
	mov	dword ptr [EBP-0060h],EAX
	mov	EAX,dword ptr [EBP-0060h]
	shr	EAX,000000008h
	mov	dword ptr [EBP-0060h],EAX
	mov	EAX,dword ptr [EBP-0060h]
	shr	EAX,000000008h
	mov	dword ptr [EBP-0060h],EAX
	mov	EAX,000000010h
	mov	word ptr [EBP-0064h],AX
	mov	EAX,dword ptr [EBP-0060h]
	push	EAX
	movsx	EAX,word ptr [EBP-0064h]
	mov	CL,AL
	pop	EAX
	shl	EAX,CL
	push	000000008h
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000926
	mov	ESI,EAX
	jmp	 $L000927
$L000926:
	xor	ESI,ESI
$L000927:
	mov	dword ptr [EBP-0068h],ESI 
	mov	EAX,dword ptr [EBP-104]
	push	EAX
	mov	EDX,0A06A5D05h
	mov	EAX,0400921D3h 
	pop	EBX
	mov	dword ptr [EBX],EDX
	mov	dword ptr [EBX+4],EAX 
	lea	EAX,OFFSET $S000773
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	mov	EAX,dword ptr [EBP-104]
	mov	EDX,dword ptr [EAX]
	mov	EAX,dword ptr [EAX+4] 
	push	EAX 
	push	EDX 
	call	 Console_WriteDouble 
	call	 Console_WriteCrLf 
	mov	EAX,dword ptr [EBP-104]
	mov	EDX,dword ptr [EAX]
	mov	EAX,dword ptr [EAX+4] 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	fstp	qword ptr [EBP-0070h]
	pop	EDX
	pop	EAX 
	lea	EAX,OFFSET $S000775
	push	000000000h
	push	EAX 
	call	 Console_WriteString
	mov	EDX,dword ptr [EBP-0070h]
	mov	EAX,dword ptr [EBP-006Ch] 
	push	EAX 
	push	EDX 
	call	 Console_WriteDouble 
	call	 Console_WriteCrLf 
	mov	EAX,dword ptr [EBP-104]
	test	EAX,EAX
	jz	OFFSET $L000928
	push	EAX
	call	 System_Memory_Destroy
$L000928:
	mov	EAX,00000000Ah
	mov	dword ptr [EBP-0078h],EAX
	mov	EAX,dword ptr [EBP-0078h]
	imul	EAX,00000000Ch
	lea	EBX,dword ptr [EAX+4]
	push	EBX
	mov	EBX,EAX
	call	 System_Memory_New
	test	EAX,EAX
	jz	 $L000929
	mov	ESI,EAX 
	mov	dword ptr [ESI],EBX 
	add	ESI,000000004h
	jmp	 $L000930
$L000929:
	xor	ESI,ESI
$L000930:
	mov	dword ptr [EBP-007Ch],ESI 
	mov	ECX,dword ptr [ESI-0004h] 
	lea	EDI,dword ptr [ESI+ECX] 
	mov	EBX,ESI 
$L000931:
	mov	ECX,EBX 
	call	 LastFeatures_DoubleProxy
	add	EBX,00000000Ch 
	cmp	EBX,EDI
	jnz	OFFSET $L000931
	mov	EAX,ESI 
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	xor	EAX,EAX
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,033333334h
	mov	EAX,040333333h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000001h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,033333334h
	mov	EAX,03FF33333h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000002h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,0F765FD8Bh
	mov	EAX,0401961E4h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000004h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,0C49BA5E4h
	mov	EAX,0401CF020h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000005h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,095182A9Ah
	mov	EAX,04028E9D4h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000006h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,0624DD2F2h
	mov	EAX,040227810h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000007h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,0DB22D0E6h
	mov	EAX,0402E3EF9h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000008h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,089374BC7h
	mov	EAX,04009E041h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	mov	EAX,000000009h
	pop	ESI
	imul	EAX,00000000Ch
	lea	ECX,dword ptr [ESI+EAX]
	lea	EAX,dword ptr [ECX+0004h]
	push	EAX
	mov	EDX,02474538Fh
	mov	EAX,040321F97h 
	push	EAX
	push	EDX 
	ffree	st
	fld	qword ptr [ESP]
	pop	EDX
	pop	EAX 
	pop	EBX
	fstp	qword ptr [EBX]
	mov	EAX,dword ptr [EBP-0078h]
	push	EAX 
	mov	EAX,dword ptr [EBP-124]
	push	EAX
	lea	ECX,dword ptr [EBP-0074h]
	call	 LastFeatures_SortDoubleProxy_Sort
	mov	EAX,dword ptr [EBP-124]
	test	EAX,EAX
	jz	OFFSET $L000932
	mov	ESI,EAX
	mov	ECX,dword ptr [ESI-0004h]
	lea	EDI,dword ptr [ESI+ECX]
	mov	EBX,ESI 
$L000933:
	mov	ECX,EBX 
	test	ECX,ECX
	jz	OFFSET $L000934
	mov	EAX,dword ptr [ECX]
	call	dword ptr [EAX+000Ch]
$L000934:
	add	EBX,00000000Ch
	cmp	EBX,EDI
	jnz	OFFSET $L000933

	add	ESI,0FFFFFFFCh
	push	ESI
	call	 System_Memory_Destroy
$L000932:
	jmp	OFFSET $L000754
$L000754:

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	retn	000000008h
LastFeatures_TestFeatures_main ENDP

__System_Hpp_Runtime_Init PROC

	push	EBP
	mov	EBP,ESP
	push	ECX 
	push	EBX 
	push	ESI 
	push	EDI 
	call	 GetVersion
	mov	 __osver,EAX ;os version
	mov	EAX, __osver 
	shr	EAX,000000008h
	and	EAX,0000000FFh
	mov	 __winminor,EAX ;windows minor
	mov	ECX, __osver 
	and	ECX,0000000FFh 
	mov	 __winmajor,ECX ;windows major
	mov	EDX,dword ptr __winmajor 
	shl	EDX,000000008h
	add	EDX,dword ptr __winminor
	mov	dword ptr __winver,EDX ;windows version
	mov	EAX, __osver 
	shr	EAX,000000010h 
	and	EAX,00000FFFFh 
	mov	 __osver,EAX 
	lea	EBX,dword ptr ___argc
	push	EBX
	call	 System_GetCommandLineArgv 
	mov	dword ptr ___argv,EAX 
	push	EAX 
	mov	ECX,dword ptr ___argc 
	push	ECX 
	call	 LastFeatures_TestFeatures_main ;user entry point (stdcall calling convention)
	push	EAX 
	mov	EAX,dword ptr ___argv 
	push	EAX 
	call	 System_Memory_GetProcessHeap 
	push	EAX 
	call	 System_Memory_Free 
	call	 System_Exit 

	pop	EDI
	pop	ESI 
	pop	EBX 
	mov	ESP,EBP
	pop	EBP 
	ret	
__System_Hpp_Runtime_Init ENDP

.DATA ;data segment
@@class_vptr_vtbl@@__LastFeatures_DoubleProxy	DWORD	OFFSET LastFeatures_DoubleProxy_lessThan,
						OFFSET LastFeatures_DoubleProxy_isEqual,
						OFFSET LastFeatures_DoubleProxy_Swap,
						OFFSET LastFeatures_SimpleObject_Destructor

@@class_vptr_vtbl@@__LastFeatures_SimpleObject	DWORD	OFFSET __purecall,
						OFFSET __purecall,
						OFFSET __purecall,
						OFFSET LastFeatures_SimpleObject_Destructor

@@class_vptr_vtbl@@__LastFeatures_HObject	DWORD	OFFSET LastFeatures_HObject_Destructor

@@class_vptr_vtbl@@__LastFeatures_SwapperObject	DWORD	OFFSET LastFeatures_SwapperObject_Swap

@@class_vptr_vtbl@@__UnitTesting_Circle	DWORD	OFFSET UnitTesting_Circle_Type,
						OFFSET UnitTesting_Circle_ComputeArea,
						OFFSET UnitTesting_Circle_Name,
						OFFSET UnitTesting_Circle_Draw,
						OFFSET UnitTesting_Circle_Destructor,
						OFFSET UnitTesting_Circle_DrawSphere

@@class_vptr_vtbl@@__UnitTesting_Shape	DWORD	OFFSET __purecall,
						OFFSET __purecall,
						OFFSET __purecall,
						OFFSET __purecall,
						OFFSET __purecall

@@class_vptr_vtbl@@__UnitTesting_Square	DWORD	OFFSET UnitTesting_Square_Type,
						OFFSET UnitTesting_Square_ComputeArea,
						OFFSET UnitTesting_Square_Name,
						OFFSET UnitTesting_Square_Draw,
						OFFSET UnitTesting_Square_Destructor

@@class_vptr_vtbl@@__UnitTesting_TestVirtuals_ExponentialRV	DWORD	OFFSET UnitTesting_TestVirtuals_ExponentialRV_Sample,
						OFFSET UnitTesting_TestVirtuals_ExponentialRV_Name

@@class_vptr_vtbl@@__UnitTesting_TestVirtuals_RandomVariable	DWORD	OFFSET __purecall,
						OFFSET UnitTesting_TestVirtuals_RandomVariable_Name

@@class_vptr_vtbl@@__UnitTesting_TestVirtuals_SimpleRV	DWORD	OFFSET UnitTesting_TestVirtuals_SimpleRV_Sample,
						OFFSET UnitTesting_TestVirtuals_SimpleRV_Name

@@class_vptr_vtbl@@__UnitTesting_TestVirtuals_UniformRV	DWORD	OFFSET UnitTesting_TestVirtuals_UniformRV_Sample,
						OFFSET UnitTesting_TestVirtuals_UniformRV_Name

@@class_vptr_vtbl@@__UnitTesting_Triangle	DWORD	OFFSET UnitTesting_Triangle_Type,
						OFFSET UnitTesting_Triangle_ComputeArea,
						OFFSET UnitTesting_Triangle_Name,
						OFFSET UnitTesting_Triangle_Draw,
						OFFSET UnitTesting_Triangle_Destructor,
						OFFSET UnitTesting_Triangle_DrawPiramid

File_INVALID_HANDLE_VALUE	=	0FFFFFFFFh
File_INVALID_SET_FILE_POINTER	=	0FFFFFFFFh
UnitTesting_TestSwitch_open	=	000000001h
UnitTesting_TestSwitch_close	=	000000002h
UnitTesting_TestSwitch_write	=	000000003h
UnitTesting_TestSwitch_read	=	000000004h

$S000542 		BYTE 	"(none)",0
$S000685 		BYTE 	"**Visited object name = ",0
$S000773 		BYTE 	"*p (3.1415...)= ",0
$S000547 		BYTE 	"A simple variable",0
$S000575 		BYTE 	"An exponential variable",0
$S000565 		BYTE 	"An uniform variable",0
$S000758 		BYTE 	"Argument: [",0
$S000615 		BYTE 	"Circle",0
$S000584 		BYTE 	"Closing file...",0
$S000702 		BYTE 	"Constructing a Double Proxy...",0
$S000697 		BYTE 	"Destroying a Simple Object...",0
$S000590 		BYTE 	"Do 6, then finish",0
$S000586 		BYTE 	"Do Read from file...",0
$S000585 		BYTE 	"Do Write to file...",0
$S000588 		BYTE 	"Do for 5 and follow to 6",0
$S000617 		BYTE 	"Drawing a Circle!",0
$S000645 		BYTE 	"Drawing a Cube!",0
$S000668 		BYTE 	"Drawing a Piramid!",0
$S000622 		BYTE 	"Drawing a Sphere!",0
$S000643 		BYTE 	"Drawing a Square!",0
$S000663 		BYTE 	"Drawing a Triangle!",0
$S000591 		BYTE 	"Invalid Option : ",0
$S000583 		BYTE 	"Opening file...",0
$S000641 		BYTE 	"Square",0
$S000661 		BYTE 	"Triangle",0
$S000759 		BYTE 	"]= ",0
$S000620 		BYTE 	"destroying a Circle object...",0
$S000629 		BYTE 	"destroying a Square object...",0
$S000666 		BYTE 	"destroying a Triangle object...",0
$S000775 		BYTE 	"res (3.1415...)= ",0
$S000679 		BYTE 	"type == stCircle",0
$S000681 		BYTE 	"type == stSquare",0
$S000683 		BYTE 	"type == stTriangle",0

__osver 		DWORD 	0;Windows OS version
__winminor 		DWORD 	0;Windows minor version
__winmajor 		DWORD 	0;Windows major version
__winver 		DWORD 	0;Windows version
__computer 		BYTE 	000000020h DUP(?);Computer name
___argv 		DWORD 	0;Array of argument values
___argc 		DWORD 	0;Argument count
UnitTesting_Rnd_seed	 DWORD	0
UnitTesting_Rnd_a	 DWORD	0
UnitTesting_Rnd_m	 DWORD	0
UnitTesting_Rnd_q	 DWORD	0
UnitTesting_Rnd_r	 DWORD	0

END __System_Hpp_Runtime_Init

